const topics = [
    { id: 1, topicName: "Animals" },
    { id: 2, topicName: "Art" },
    { id: 3, topicName: "Books" },
    { id: 4, topicName: "Cars" },
    { id: 5, topicName: "Coding" },
    { id: 6, topicName: "Cooking" },
    { id: 7, topicName: "Dance" },
    { id: 8, topicName: "Education" },
    { id: 9, topicName: "Fashion" },
    { id: 10, topicName: "Finance" },
    { id: 11, topicName: "Fitness" },
    { id: 12, topicName: "Food" },
    { id: 13, topicName: "Gaming" },
    { id: 14, topicName: "Health" },
    { id: 15, topicName: "History" },
    { id: 16, topicName: "Languages" },
    { id: 17, topicName: "Movies" },
    { id: 18, topicName: "Music" },
    { id: 19, topicName: "Nature" },
    { id: 20, topicName: "Photography" },
    { id: 21, topicName: "Politics" },
    { id: 22, topicName: "Science" },
    { id: 23, topicName: "Shopping" },
    { id: 24, topicName: "Space" },
    { id: 25, topicName: "Sports" },
    { id: 26, topicName: "Technology" },
    { id: 27, topicName: "Travel" },
    { id: 28, topicName: "TV Shows" },
    { id: 29, topicName: "Writing" },
    { id: 30, topicName: "Yoga" }
];

export default topics;
